// <auto-generated />
namespace Projectwerk.Vermeersch.f.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class opnieuw : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(opnieuw));
        
        string IMigrationMetadata.Id
        {
            get { return "201803071913312_opnieuw"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
